site_name: MR AV DOCS BLOGS
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - blog
    - social
    - navigation.instant
    - navigation.instant
    - navigation.instant.prefetch
     
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  